### PR TITLE
allow use of LM-Studio

### PR DESCRIPTION
**Pull request by meirm**
Optionally add BASE_URL to .env.local to take effect

### CODE REVIEW

**Review by rahulnyk — CHANGES_REQUESTED** [review]
in my opinion these changes are not required any more. 

here are the comments from the openai class documentation. 

```

baseURL?: string | null | undefined;

  /**
   * The maximum amount of time (in milliseconds) that the client should wait for a response
   * from the server before timing out a single request.
   *
   * Note that request timeouts are retried by default, so in a worst-case scenario you may wait
   * much longer than this timeout before the promise succeeds or fails.
   */

```

So as long as the env variable is defined in the .env.local file, the code should work without any change. 

Please test and let me know.

**Comment by meirm** [comment]
May be I wasn't clear enough. Using the openai api by default it uses openai endpoint. using the patch I added it allows you to point the openai object to direct its api to another URL. Being able to set the base url allows you to point the api to use local hosted models. In my case I am using LM-Studio to use llama3 for inference and nomic-ai for embeddings.
With this changes I am able to run Fountain pen offline.

**Comment by rahulnyk** [comment]
> May be I wasn't clear enough. Using the openai api by default it uses openai endpoint. using the patch I added it allows you to point the openai object to direct its api to another URL. Being able to set the base url allows you to point the api to use local hosted models. In my case I am using LM-Studio to use llama3 for inference and nomic-ai for embeddings. With this changes I am able to run Fountain pen offline.

Yes, I understand. 
But I still feel if you add `OPENAI_BASE_URL` to your .env.local, it should work even without the patch. 
effectively, the openai lib always defaults to the env variable `OPENAI_BASE_URL`
```
baseURL?: string | null | undefined;

/**
   * Override the default base URL for the API, e.g., "https://api.example.com/v2/"
   *
   * Defaults to process.env['OPENAI_BASE_URL'].
   */
```

Can you please test and confirm? If it does not work, then I will merge this PR.

**Comment by meirm** [comment]
You are correct.

**Pull request closed without merging**
